### ISSUE TITLE
SSL Timeout on S3 get_contents_to_file

### ISSUE THREAD

**Issue by 7h3kk1d** [boto/boto#2409]
I'm getting the error when pulling files from S3. The instance is running in Ec2. And this happens infrequently: 

```
  File "sippythrift/application.py", line 186, in csv_generator_action
  filepath = t.retrieve_file(message["key"])
  File "sippythrift/thriftfiles.py", line 18, in retrieve_file
  k.get_contents_to_filename(filename)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1665, in get_contents_to_filename
    response_headers=response_headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1603, in get_contents_to_file
   response_headers=response_headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1435, in get_file
query_args=None)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1488, in     _get_file_internal
for bytes in self:
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 368, in next
    data = self.resp.read(self.BufferSize)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 416, in read
    return httplib.HTTPResponse.read(self, amt)
  File "/usr/lib/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out
```

**Comment by rouge8** [comment]
I'm seeing this as well when downloading a few thousand ~25mb files on an EC2 instance in us-east-1.

**Comment by somada141** [comment]
I've been getting the same error when iterating over a `BucketListResultSet` reading a massive bucket (several million entries). I actually get that error simply by getting the keys out of the iterator (without even calling the 'get_contents_*' methods.

Has anyone made any progress on this issue in general?

Is there anyway to catch the error, wait a couple seconds and then resume iteration where one left off?

**Comment by tedder** [comment]
there's a way to catch the error and retry. See my pull request.

**Comment by raptortalons** [comment]
I'm getting this issue too from time to time when downloading files of approx. 20 MB.

I've started keeping track of the files this happens for to see if it's the same ones.

How can I determine if this is a network issue?

**Comment by curiousjgeorge** [comment]
For those that are encountering the issue, what version of Boto are you using? I ran into the same issue with an older version, but it was resolved by upgrading. I think a commit in connection.py for version 2.14 fixed the issue.

**Comment by raptortalons** [comment]
I am using version 2.38.0

**Comment by tedder** [comment]
@curiousjgeorge what commit are you talking about?

**Comment by curiousjgeorge** [comment]
@tedder It was commit 89c6fa90d714854afd79cdc1fbec91fd03381b5c (link: https://github.com/boto/boto/commit/89c6fa90d714854afd79cdc1fbec91fd03381b5c )

**Comment by robtandy** [comment]
Upgrading and this still happens to me 10x a day out of maybe 250k requests.   Using version 2.38.0 and python 2.7.6.

Stack trace is:
....
    data = k.get_contents_as_string()
  File "XXX/local/lib/python2.7/site-packages/boto/s3/key.py", line 1782, in get_contents_as_string
    response_headers=response_headers)
  File "XXX/local/lib/python2.7/site-packages/boto/s3/key.py", line 1650, in get_contents_to_file
    response_headers=response_headers)
  File "XXX/local/lib/python2.7/site-packages/boto/s3/key.py", line 1482, in get_file
    query_args=None)
  File "XXX/local/lib/python2.7/site-packages/boto/s3/key.py", line 1535, in _get_file_internal
    for bytes in self:
  File "XXX/local/lib/python2.7/site-packages/boto/s3/key.py", line 386, in next
    data = self.resp.read(self.BufferSize)
  File "XXX/local/lib/python2.7/site-packages/boto/connection.py", line 413, in read
    return http_client.HTTPResponse.read(self, amt)
  File "/usr/lib/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out

**Comment by saurabh24292** [comment]
This is pretty annoying. It runs on one network while gives SSLError on another network. What to do if switching the network is not an option?

**Comment by RvKmR-WaGh** [comment]
Seems the problem with network speed. try on different network.
